language: c
sudo: required
node: 
matrix:
  include:
  # - os: osx # TODO: Re-enable once Travis OSX is good
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
node_js:
- '7'
before_install: 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends
    -y icnsutils graphicsmagick xz-utils; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export RELEASE_FILE_PATH='release/linux-unpacked/appium-desktop'; fi     
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export RELEASE_FILE_PATH='release/mac/Appium.app'; fi
  - echo "Deploying to $RELEASE_FILE_PATH" 
addons:
  apt:
    packages: 
      - xvfb
before_script:
- node --version
- npm install
- npm install -g electron
- node --version
- npm run package || true

cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
script:
- npm run e2e
install:
- nvm install 7
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
dist: trusty
deploy:
  provider: releases
  skip_cleanup: true
  file:'$RELEASE_FILE_PATH'
  api_key:
    secure: oEQR3OIKVftqOwPOagzN7/RPw4fJjK64gbg4ziq9TUcsMSKHxI5kpoWLJPnahyMtO7Vkj6ee7Xy3QJXPJ1fl0ZX7Mo8P3t+bl3bKMfQBv1ld6iBMgrNxnB0ABd9084n4pfYAbV7N5g5ZkX9oV4ExcJWPKD2eSp3AaiyguPit3JpGwlSOsJByg1vCmB9yDgfo5dih9gEuId+tF/1ylpATqA+3rijtRdNOmoTTNXxmN+o/Hu8GzqP8LmlucGUqOKIyhM46/6ypWVtTWpmu5KAx3qXkqTed/S4I+VZ1EC7EigXPX2MD09w2/d44udGWJGAHVSGDNUTH3Kex6QT/2VPJ72CKUm7RV/xrKudx+6MhprbYkcsi0HdcbpMz0c3L30ps6src3S1zBQHC69RZrL/5WgFdEm0uG/i//SaYVuAD1dO7+0lBxnPqQrft3sdj6qOkAP1w9cUbNeYTihojyzTlgbrL1XsGji3M2Ir0DF4AxRdFI2vnyEmrZDtJKynGYBlfMFFc9RGTrFGSq1hP03/E7Hhg+BOnMDrfkPM2TXlj/xdhxeRzC9qtUwVyulEQrsdHV0ALzwC4eXR/w0xygABqhTM8GxodPQmBK1W9sP9DZy0YiEzWwMPKsWYkSDyqXUcfkX+sp37d0lTuWpDjWzyZ3GYrT+6STVTnyU5NZ5FT6VE=
  on:
    repo: dpgraham/appium-desktop
    tags: true
