environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run package
  # - npm run e2e-win
  - npm run deploy-win-exe

build: off

artifacts:
  - path: 'release\Appium*.exe'